<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class RolePermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 
     * This seeder creates the super_admin role required for UserSeeder.
     * Other permissions are auto-generated by:
     * - Filament Shield: `php artisan shield:generate --all --panel=admin`
     * - Lab permissions: LabPermissionServiceProvider (creates lab_{slug}_{action} permissions dynamically)
     * 
     * Run this BEFORE UserSeeder.
     */
    public function run(): void
    {
        // Reset cached roles and permissions
        app()[PermissionRegistrar::class]->forgetCachedPermissions();

        // Create super_admin role - required by UserSeeder
        // Super admin has all permissions via Gate::before in AuthServiceProvider
        Role::firstOrCreate(['name' => 'super_admin', 'guard_name' => 'web']);

        $this->command->info('✅ Role super_admin created successfully!');
        $this->command->newLine();
        $this->command->info('📌 Next steps:');
        $this->command->info('   1. Run: php artisan db:seed --class=UserSeeder');
        $this->command->info('   2. Run: php artisan shield:generate --all --panel=admin');
        $this->command->info('   3. Configure lab permissions via Filament Shield UI (/admin/shield/roles)');
    }
}
